name: Node.js CI and Deploy (placeholder)
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install & test backend
        run: |
          cd backend
          npm ci
          npm test || true
